### ISSUE TITLE
微信开发工具是怎么回事

### ISSUE THREAD

**Issue by qwIvan** [levinit/aur-pkgbuilds#1]
![image](https://user-images.githubusercontent.com/7613160/46590989-31b67800-caea-11e8-9333-03a6cead53e9.png)

> 全部安装大小：  786.01 MiB
> 净更新大小：  563.66 MiB

**Comment by levinit** [comment]
怎么了？ 
现在更到0926了

**Comment by qwIvan** [comment]
還是很大
